### ISSUE TITLE
This is not a issue i just wanted to ask something Read My Comment

### ISSUE THREAD

**Issue by Abhi5006** [nymda/WinTerrEdit#12]
Sir i am trying to study how softwares like yours WinTerraEdit reads the .plr file.
i looked into the code and in the file crypto.cs i found it but i am thinking to myself how could it be so easy .
or is it not please help

**Comment by nymda** [comment]
Hey, i didnt see this before, sorry.

its very simple to decrypt the .plr files into a readable state, but once they are decrypted you still need to know what the data means. Look at the function "LoadData" under "Entry.cs"
