### ISSUE TITLE
Missing item

### ISSUE THREAD

**Issue by BeanGalSolina** [nymda/WinTerrEdit#15]
The S.D.M.G. (Space Dolphin Machine Gun) Is missing from the items menu

**Comment by BeanGalSolina** [comment]
Solar breastplate is also missing

**Comment by nymda** [comment]
Hello, both these items are present. 
there is a known bug causing things to not appear if you use capitalization.
sorry for the inconvenience.  

![image](https://user-images.githubusercontent.com/16545187/109326436-1a10f300-784f-11eb-8a4d-1a7837f8f6d8.png)
![image](https://user-images.githubusercontent.com/16545187/109326469-24cb8800-784f-11eb-89db-8a8e8f7e1232.png)

**Comment by BeanGalSolina** [comment]
oh ok
