### ISSUE TITLE
Support for tModLoader custom items

### ISSUE THREAD

**Issue by IncubusRK** [nymda/WinTerrEdit#2]
Please add support for items added in mods.
Let at least an item be marked as unknown, but not deleted.

**Comment by nymda** [comment]
I will look into this, please could you upload your .PLR file here as i do not have any mods installed at the moment. As far as i can tell, they all work differently. Thanks.

**Comment by IncubusRK** [comment]
Player file [Zak.zip](https://github.com/nymda/WinTerrEdit/files/4790827/Zak.zip)
enabled mod's:  "BossChecklist",   "CalamityMod",  "RecipeBrowser",  "ReducedGrinding",  "CalamityModMusic",  "ThoriumMod",  "HamstarHelpers",  "TerrariaOverhaul",  "MaxStackExtra"

**Comment by nymda** [comment]
Ive done some looking into this and it doesnt seem that terraria stores modded items in the same place as normal ones. However ive added a way of detecting and notifying the user of when this happens. 

If i find some way of finding out what the items are in the future, i will put it in, but for now there isnt much i can do
