### ISSUE TITLE
Cyrillic alphabet isn't supported

### ISSUE THREAD

**Issue by exivard** [nymda/WinTerrEdit#5]
Hello,
First of all,  I want to thank you for creating this program.
As a user that use Cyrillic, I want to notify you about the problem with saving nicknames in russian.
After saving, nickname turns into a random symbols or sometimes doesn't changes at all.
.plr file which contains Cyrillic letters doesn't change it name in Terraria\Players
That's all issues i had found, have a nice day!

**Comment by nymda** [comment]
Hello, thanks for using my program! Sorry you had an issue with it, i will take a look at this soon

**Comment by nymda** [comment]
This has been fixed in the latest release, please let me know if there are any more issues.

please note that the .PLR files name does not change along with the players name, the .PLR file is named independently when saving.

**Comment by exivard** [comment]
> This has been fixed in the latest release, please let me know if there are any more issues.
> 
> please note that the .PLR files name does not change along with the players name, the .PLR file is named independently when saving.

Now it's works! Thanks you for your service, bro.

**Comment by nymda** [comment]
happy to help :)
