### ISSUE TITLE
Spectral mask problem

### ISSUE THREAD

**Issue by exivard** [nymda/WinTerrEdit#8]
Hello, I want to notify about a problem with Spectral mask ![Spectral Mask](https://user-images.githubusercontent.com/38617906/90565253-4b797980-e1af-11ea-8000-06f0da4333eb.png)
When I choose an inventory with a Spectral Mask in armor slot this error is happening
![WTE-Standalone_x9hVpXnCMB](https://user-images.githubusercontent.com/38617906/90565585-d22e5680-e1af-11ea-8bd1-6801ec3a05f3.png)
And program looks like 
![WTE-Standalone_amPjZnjDAE](https://user-images.githubusercontent.com/38617906/90565757-191c4c00-e1b0-11ea-8868-5d2171ca4d07.png)
I can't change all of this features and add new items.

**Comment by nymda** [comment]
hmm thats pretty odd, could you attach your .plr file here? thanks. 
also, try using the beta of 1.10.0 and see if the same happens there

**Comment by exivard** [comment]
Still not working with beta build.

[Builder.zip](https://github.com/nymda/WinTerrEdit/files/5099652/Builder.zip)

**Comment by exivard** [comment]
Perhaps, some items may have same problem, IDK which one can cause similar problem.

**Comment by nymda** [comment]
Sorry this took so long, ive been on holiday. the issue was caused by having 260 mana which is above the maximum i had set to display. I will fix this for the next release.

**Comment by exivard** [comment]
No problem, you are a developer and you decide what and when to do 😄
