### ISSUE TITLE
Treasure bags default to king slime

### ISSUE THREAD

**Issue by amb2127** [nymda/WinTerrEdit#9]
When I click on a treasure bag it automatically defaults to King Slime for no reason.

![image](https://user-images.githubusercontent.com/39502367/90837851-31f83f00-e321-11ea-92f7-0196fff08219.png)

I don't know if this is an issue on my end but I thought I'd point this out.

**Comment by nymda** [comment]
Sorry about this issue, it will be fixed in the next update.
